#!/usr/bin/bash

src="${1:-.}"
prefix=${2:-wd}

if [ ! -d "$src" ]; then
    exit 1
fi

declare -A nodes

defwd() {
    local key=${1%.*}
    if [ $key == $1 ]; then
        return 1
    fi
    if [ -z ${nodes[$key]} ]; then
        nodes[$key]=1
        defwd $key
        if [ $? -eq 1 ]; then
            local module=${key#.}
            echo -e "local $module = require(\"$module\")"
        fi
        echo -en "$prefix.$key = {}\n\n"
    fi
    return 0
}

cat <<END
-- THIS FILE WAS AUTOGENERATED - DO NOT MODIFY --

---@class $prefix
---@operator call: wibox.widget.base
local $prefix = {}

END

for wd in $(find "$src" -name "*.lua" -exec grep -Pho '\b'$prefix'(\.\w+)+\b' {} + | sort | uniq); do
    twd=${wd#$prefix.}
    defwd $twd
    cat <<END
---@param args $wd
---@return $wd
function $wd(args) args.layout = $twd; return args; end

END
done

if [ -z ${nodes[wibox]} ]; then
    nodes[wibox]=1
    echo "local wibox = require(\"wibox\")"
fi
echo "local base = wibox.widget.base"
echo "return setmetatable(wd, { __call = function(_, args) return base.make_widget_declarative(args) end })"
