---@meta _
---@todo

---@class client
---@field window unknown
---@field name unknown
---@field skip_taskbar unknown
---@field type unknown
---@field class unknown
---@field instance unknown
---@field pid unknown
---@field role unknown
---@field machine unknown
---@field icon_name unknown
---@field icon unknown
---@field icon_sizes unknown
---@field screen unknown
---@field hidden unknown
---@field minimized unknown
---@field size_hints_honor unknown
---@field border_width unknown
---@field border_color unknown
---@field urgent unknown
---@field content unknown
---@field opacity unknown
---@field ontop unknown
---@field above unknown
---@field below unknown
---@field fullscreen unknown
---@field maximized unknown
---@field maximized_horizontal unknown
---@field maximized_vertical unknown
---@field transient_for unknown
---@field group_window unknown
---@field leader_window unknown
---@field size_hints unknown
---@field motif_wm_hints unknown
---@field sticky unknown
---@field modal unknown
---@field focusable unknown
---@field shape_bounding unknown
---@field shape_clip unknown
---@field shape_input unknown
---@field client_shape_bounding unknown
---@field client_shape_clip unknown
---@field startup_id unknown
---@field valid unknown
---@field first_tag unknown
---@field buttons unknown
---@field keys unknown
---@field marked unknown
---@field is_fixed unknown
---@field immobilized_horizontal unknown
---@field immobilized_vertical unknown
---@field floating unknown
---@field x unknown
---@field y unknown
---@field width unknown
---@field height unknown
---@field dockable unknown
---@field requests_no_titlebar unknown
---@field shape unknown
---@field active unknown
---@field struts unknown
---@field isvisible unknown
---@field kill unknown
---@field swap unknown
---@field tags unknown
---@field raise unknown
---@field lower unknown
---@field unmanage unknown
---@field geometry unknown
---@field apply_size_hints unknown
---@field get_icon unknown
---@field jump_to unknown
---@field append_keybinding unknown
---@field remove_keybinding unknown
---@field append_mousebinding unknown
---@field remove_mousebinding unknown
---@field to_primary_section unknown
---@field to_secondary_section unknown
---@field relative_move unknown
---@field move_to_tag unknown
---@field toggle_tag unknown
---@field move_to_screen unknown
---@field to_selected_tags unknown
---@field get_transient_for_matching unknown
---@field is_transient_for unknown
---@field activate unknown
---@field grant unknown
---@field deny unknown
---@field disconnect_signal unknown
---@field emit_signal unknown
---@field connect_signal unknown
---@field weak_connect_signal unknown
local C


---@class _client
---@field focus client|nil # The focused `client` or `nil` (in case there is none).
---@field instances unknown
---@field get unknown
---@field disconnect_signal unknown
---@field emit_signal unknown
---@field connect_signal unknown
local M

return M
